# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setStyleSheet("background-color: rgb(243, 243, 243)")
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(0, 40, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.NavigationInterface = NavigationInterface(MainWindow)
        self.NavigationInterface.setMinimumSize(QtCore.QSize(48, 15))
        self.NavigationInterface.setObjectName("NavigationInterface")
        self.gridLayout.addWidget(self.NavigationInterface, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(MainWindow)
        self.stackedWidget.setStyleSheet("QStackedWidget  {\n"
"    border: 1px solid rgb(229, 229, 229);\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 10px;\n"
"    background-color: rgb(249, 249, 249);\n"
"}\n"
"\n"
"QStackedWidget * {\n"
"border: none;\n"
"background-color: transparent;\n"
"\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
from qfluentwidgets import NavigationInterface
