# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_other.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(943, 658)
        Form.setMinimumSize(QtCore.QSize(943, 658))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit_keyword = LineEdit(Form)
        self.line_edit_keyword.setObjectName("line_edit_keyword")
        self.horizontalLayout.addWidget(self.line_edit_keyword)
        self.pushbutton_query = PushButton(Form)
        self.pushbutton_query.setMinimumSize(QtCore.QSize(200, 0))
        self.pushbutton_query.setObjectName("pushbutton_query")
        self.horizontalLayout.addWidget(self.pushbutton_query)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(319, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushbutton_previous_page = PushButton(Form)
        self.pushbutton_previous_page.setObjectName("pushbutton_previous_page")
        self.horizontalLayout_2.addWidget(self.pushbutton_previous_page)
        self.label_pages = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(14)
        self.label_pages.setFont(font)
        self.label_pages.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pages.setObjectName("label_pages")
        self.horizontalLayout_2.addWidget(self.label_pages)
        self.pushbutton_next_page = PushButton(Form)
        self.pushbutton_next_page.setObjectName("pushbutton_next_page")
        self.horizontalLayout_2.addWidget(self.pushbutton_next_page)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 3)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(28)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushbutton_add = PrimaryPushButton(Form)
        self.pushbutton_add.setMinimumSize(QtCore.QSize(150, 0))
        self.pushbutton_add.setObjectName("pushbutton_add")
        self.horizontalLayout_3.addWidget(self.pushbutton_add)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        self.TableWidget = TableWidget(Form)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.TableWidget, 3, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushbutton_query.setText(_translate("Form", "查询"))
        self.pushbutton_previous_page.setText(_translate("Form", "上一页"))
        self.label_pages.setText(_translate("Form", "1/1"))
        self.pushbutton_next_page.setText(_translate("Form", "下一页"))
        self.label_title.setText(_translate("Form", "XXX Manger"))
        self.pushbutton_add.setText(_translate("Form", "添加新记录"))
from qfluentwidgets import LineEdit, PrimaryPushButton, PushButton, TableWidget
