# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewSetting(object):
    def setupUi(self, ViewSetting):
        ViewSetting.setObjectName("ViewSetting")
        ViewSetting.resize(943, 658)
        ViewSetting.setMinimumSize(QtCore.QSize(943, 658))
        self.verticalLayout = QtWidgets.QVBoxLayout(ViewSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(ViewSetting)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(28)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(319, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(ViewSetting)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ViewSetting)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_edit_pwd = PushButton(ViewSetting)
        self.button_edit_pwd.setMinimumSize(QtCore.QSize(100, 35))
        self.button_edit_pwd.setObjectName("button_edit_pwd")
        self.horizontalLayout.addWidget(self.button_edit_pwd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ViewSetting)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.switch_button_otpset = CustomSwitchButton(ViewSetting)
        self.switch_button_otpset.setMinimumSize(QtCore.QSize(100, 35))
        self.switch_button_otpset.setObjectName("switch_button_otpset")
        self.horizontalLayout_2.addWidget(self.switch_button_otpset)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 450, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(ViewSetting)
        QtCore.QMetaObject.connectSlotsByName(ViewSetting)

    def retranslateUi(self, ViewSetting):
        _translate = QtCore.QCoreApplication.translate
        ViewSetting.setWindowTitle(_translate("ViewSetting", "Form"))
        self.label_title.setText(_translate("ViewSetting", "用户设置"))
        self.label.setText(_translate("ViewSetting", "修改密码"))
        self.button_edit_pwd.setText(_translate("ViewSetting", "修改密码"))
        self.label_2.setText(_translate("ViewSetting", "设置2FA"))
        self.switch_button_otpset.setOnText(_translate("ViewSetting", "开启OTP"))
        self.switch_button_otpset.setOffText(_translate("ViewSetting", "关闭OTP"))
from my_button import CustomSwitchButton
from qfluentwidgets import PushButton
