# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_view_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewMain(object):
    def setupUi(self, ViewMain):
        ViewMain.setObjectName("ViewMain")
        ViewMain.resize(943, 658)
        ViewMain.setMinimumSize(QtCore.QSize(943, 658))
        ViewMain.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ViewMain)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 200)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(ViewMain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resource/image/mainwindows-bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_username = QtWidgets.QLabel(ViewMain)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(26)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.verticalLayout_3.addWidget(self.label_username)
        self.label_greeting = QtWidgets.QLabel(ViewMain)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN VF Medium")
        font.setPointSize(14)
        self.label_greeting.setFont(font)
        self.label_greeting.setObjectName("label_greeting")
        self.verticalLayout_3.addWidget(self.label_greeting)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 343, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(ViewMain)
        QtCore.QMetaObject.connectSlotsByName(ViewMain)

    def retranslateUi(self, ViewMain):
        _translate = QtCore.QCoreApplication.translate
        ViewMain.setWindowTitle(_translate("ViewMain", "Form"))
        self.label_username.setText(_translate("ViewMain", "Womsxd"))
        self.label_greeting.setText(_translate("ViewMain", "早上好，今天要做点什么？"))
import resource_rc
